#!/bin/bash

#cp msd338/out/target/common/obj/JAVA_LIBRARIES/com.mstar.android.ext_intermediates/classes.jar   com.mstar.android.ext.jar
rootdir()
{
    thedir=`pwd`

    if [ -d "${thedir}/build" -a  -f "${thedir}/build/envsetup.sh" -a -f  "${thedir}/build/core/config.mk" ]; then
       echo "${thedir}"
    else
    	while [ ! -d "${thedir}/build" -o ! -f "${thedir}/build/envsetup.sh" -o ! -f  "${thedir}/build/core/config.mk" ]; do
    		#statements
    		thedir=`cd .. && pwd`
                echo "thedir is ${thedir}"
    		if [[ "${thedir}" = "/" ]]; then 
    			echo ""
    			return
    		fi
    	done
    	echo "${thedir}"
    fi
}

myroot=$(rootdir)
if [[ ! -d  ${myroot}/out ]]; then
	#statements
	echo "please make your project first...."
	exit
fi

rm -rf ${myroot}/jars
mkdir ${myroot}/jars

jars="$(find ${myroot}/out/target/common/obj/JAVA_LIBRARIES/   -name classes.jar)"
#echo ${filename}
for jarfile in $jars; do
	#echo ${jarfile}
    filename=$(dirname ${jarfile})
	#filename=${filename##*/}
	filename=$(basename ${filename})
	filename=${filename%_intermediates}.jar
	#echo -e "\t${filename}"
	#echo -e "\tjarfile is ${jarfile}"
	cp -f ${jarfile}  ${myroot}/jars/${filename}
done
