#!/bin/bash

dst_ip=${2}
dst_file=${3}
dst_file_name=$(basename ${dst_file} .apk)
system_apk_path="/system/app"
is_638=${1:-0}

function usage()
{
    echo "USAGE: $0 <0/1>[638 or not] <ip>[dest tv ip] <apk>[/path/to/apk  ref to current folder] "
}


# check param
if [[ ! $dst_ip =~ [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ ]]; then
#if [[ ! "$dst_ip" =~ "\d+\.\d+\.\d+\.\d+" ]]; then
	echo "dst_ip is not right: ${dst_ip}"
	usage
	exit
fi

if [[ -z "$dst_file" || -z "$dst_file_name" ]]; then
	echo "dst_file is not right: ${dst_file}"
	usage
	exit
fi

if [[ ! -f "$dst_file" ]]; then
	echo "dst_file is not exist: ${dst_file}"
	usage
	exit
fi

if [[ ${is_638} != "0" ]]; then
	system_apk_path=${system_apk_path}/${dst_file_name}	
fi

echo -e "\033[0;31m"
echo "is 638 system:  $is_638"
echo "sytem_apk_path is ${system_apk_path}"
echo "src file is ${dst_file}"
echo -e "\033[0m"

echo -n 
read -p "coninue?[y/n]" yes_or_no

if [[ ${yes_or_no} != "y" && ${yes_or_no} != "Y" ]]; then
	exit
fi

adb kill-server && adb connect $dst_ip && sleep 0.1 && adb root && sleep 0.2 && adb connect $dst_ip && sleep 0.1 && adb remount && \
adb push "$dst_file"  "${system_apk_path}/$dst_file_name.apk" 
#adb install -r "${system_apk_path}/$dst_file_name.apk"
adb shell pm  install -r "${system_apk_path}/$dst_file_name.apk"
sleep 0.2
adb disconnect
adb kill-server
